// <auto-generated />
namespace assn2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NOREGEX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NOREGEX));
        
        string IMigrationMetadata.Id
        {
            get { return "201504090354509_NOREGEX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
